In [1]:
import pandas as pd
import numpy as np

In [2]:
df_hr=pd.read_csv("hr.csv") #abrimos el dataframe.
df_hr.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41.0,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80.0,0,8,0.0,1,6,4,0,5.0
1,49.0,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,NaN,1,10,3.0,3,10,7,1,7.0
2,37.0,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,NaN,0,7,3.0,3,0,0,0,0.0
3,33.0,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80.0,0,8,3.0,3,8,7,3,0.0
4,27.0,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80.0,1,6,3.0,3,2,2,2,2.0

In [3]:
df_hr.info() #aqui  nos muestra la informacion de nuestro dataframe, nos muestra info como columnasxfilas,los valores no nulos, tipos de datos

<class 'pandas.DataFrame'>
RangeIndex: 1474 entries, 0 to 1473
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1401 non-null   float64
 1   Attrition                 1474 non-null   str
 2   BusinessTravel            1357 non-null   str
 3   DailyRate                 1474 non-null   int64
 4   Department                1445 non-null   str
 5   DistanceFromHome          1474 non-null   int64
 6   Education                 1474 non-null   int64
 7   EducationField            1416 non-null   str
 8   EmployeeCount             1474 non-null   int64
 9   EmployeeNumber            1474 non-null   int64
 10  EnvironmentSatisfaction   1474 non-null   int64
 11  Gender                    1474 non-null   str
 12  HourlyRate                1474 non-null   int64
 13  JobInvolvement            1474 non-null   int64
 14  JobLevel                  1474 non-null   int64
 15  JobRole                   1474 non-null   str
 16  JobSatisfaction           1445 non-null   float64
 17  MaritalStatus             1342 non-null   str
 18  MonthlyIncome             1460 non-null   float64
 19  MonthlyRate               1474 non-null   int64
 20  NumCompaniesWorked        1474 non-null   int64
 21  Over18                    1474 non-null   str
 22  OverTime                  1430 non-null   str
 23  PercentSalaryHike         1474 non-null   int64
 24  PerformanceRating         1474 non-null   int64
 25  RelationshipSatisfaction  1474 non-null   int64
 26  StandardHours             1310 non-null   float64
 27  StockOptionLevel          1474 non-null   int64
 28  TotalWorkingYears         1474 non-null   int64
 29  TrainingTimesLastYear     1386 non-null   float64
 30  WorkLifeBalance           1474 non-null   int64
 31  YearsAtCompany            1474 non-null   int64
 32  YearsInCurrentRole        1474 non-null   int64
 33  YearsSinceLastPromotion   1474 non-null   int64
 34  YearsWithCurrManager      1326 non-null   float64
dtypes: float64(6), int64(20), str(9)
memory usage: 403.2 KB

In [4]:
df_hr.describe() # nos describe informacion como media,mediana,porcentiles ect

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1401.000000,1474.000000,1474.000000,1474.000000,1474.0,1474.000000,1474.000000,1474.000000,1474.000000,1474.000000,...,1474.000000,1310.0,1474.000000,1474.000000,1386.000000,1474.000000,1474.000000,1474.000000,1474.000000,1326.000000
mean,36.944325,802.702171,9.199457,2.911126,1.0,1024.471506,2.723881,65.887381,2.729986,2.063772,...,2.713704,80.0,0.794437,11.274084,2.797980,2.761872,6.996608,4.221845,2.183175,4.061840
std,9.105009,403.539530,8.104266,1.024267,0.0,602.421193,1.093280,20.310444,0.712861,1.106055,...,1.080338,0.0,0.851784,7.785972,1.296882,0.705625,6.122920,3.622032,3.219356,3.517603
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,488.750000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,803.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [5]:
df_hr.isnull().sum() #aqui nos muestra el numero de nulos que hay por columna.

Age                          73
Attrition                     0
BusinessTravel              117
DailyRate                     0
Department                   29
DistanceFromHome              0
Education                     0
EducationField               58
EmployeeCount                 0
EmployeeNumber                0
EnvironmentSatisfaction       0
Gender                        0
HourlyRate                    0
JobInvolvement                0
JobLevel                      0
JobRole                       0
JobSatisfaction              29
MaritalStatus               132
MonthlyIncome                14
MonthlyRate                   0
NumCompaniesWorked            0
Over18                        0
OverTime                     44
PercentSalaryHike             0
PerformanceRating             0
RelationshipSatisfaction      0
StandardHours               164
StockOptionLevel              0
TotalWorkingYears             0
TrainingTimesLastYear        88
WorkLifeBalance               0
YearsAtCompany                0
YearsInCurrentRole            0
YearsSinceLastPromotion       0
YearsWithCurrManager        148
dtype: int64

In [6]:
(df_hr.isnull().mean()*100).sort_values(ascending=False) # aqui nos muesta el numero de nulos en porcentaje y oredenado en orde ascendente.

StandardHours               11.126187
YearsWithCurrManager        10.040706
MaritalStatus                8.955224
BusinessTravel               7.937585
TrainingTimesLastYear        5.970149
Age                          4.952510
EducationField               3.934871
OverTime                     2.985075
JobSatisfaction              1.967436
Department                   1.967436
MonthlyIncome                0.949796
Attrition                    0.000000
EmployeeNumber               0.000000
EmployeeCount                0.000000
Gender                       0.000000
EnvironmentSatisfaction      0.000000
Education                    0.000000
DistanceFromHome             0.000000
DailyRate                    0.000000
JobRole                      0.000000
HourlyRate                   0.000000
JobInvolvement               0.000000
JobLevel                     0.000000
Over18                       0.000000
PercentSalaryHike            0.000000
NumCompaniesWorked           0.000000
MonthlyRate                  0.000000
RelationshipSatisfaction     0.000000
PerformanceRating            0.000000
TotalWorkingYears            0.000000
StockOptionLevel             0.000000
WorkLifeBalance              0.000000
YearsAtCompany               0.000000
YearsInCurrentRole           0.000000
YearsSinceLastPromotion      0.000000
dtype: float64

In [7]:
round(df_hr.isna().sum().sort_values(ascending=False)/df_hr.shape[0]*100,2) # nos quedamos con esta opcion.aqui nos muesta el numero de nulos en porcentaje y oredenado en orde ascendente.

StandardHours               11.13
YearsWithCurrManager        10.04
MaritalStatus                8.96
BusinessTravel               7.94
TrainingTimesLastYear        5.97
Age                          4.95
EducationField               3.93
OverTime                     2.99
JobSatisfaction              1.97
Department                   1.97
MonthlyIncome                0.95
Attrition                    0.00
EmployeeNumber               0.00
EmployeeCount                0.00
Gender                       0.00
EnvironmentSatisfaction      0.00
Education                    0.00
DistanceFromHome             0.00
DailyRate                    0.00
JobRole                      0.00
HourlyRate                   0.00
JobInvolvement               0.00
JobLevel                     0.00
Over18                       0.00
PercentSalaryHike            0.00
NumCompaniesWorked           0.00
MonthlyRate                  0.00
RelationshipSatisfaction     0.00
PerformanceRating            0.00
TotalWorkingYears            0.00
StockOptionLevel             0.00
WorkLifeBalance              0.00
YearsAtCompany               0.00
YearsInCurrentRole           0.00
YearsSinceLastPromotion      0.00
dtype: float64

In [8]:
# ver duplicados
df_hr.duplicated().sum() #aqui nos muestra cuantos valores hay duplicados ( en realidad seran 8)

np.int64(4)

In [9]:
df_hr[df_hr.duplicated()] # me aparece distintas!

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1470,28.0,No,Travel_Rarely,866,Sales,5,3,Medical,1,1469,...,4,NaN,0,6,4.0,3,5,4,1,NaN
1471,53.0,No,Travel_Rarely,1084,Research & Development,13,2,Medical,1,250,...,3,NaN,2,5,3.0,3,4,2,1,3.0
1472,24.0,Yes,Travel_Rarely,240,Human Resources,22,1,Human Resources,1,1714,...,3,80.0,1,1,2.0,3,1,0,0,0.0
1473,45.0,No,Travel_Rarely,1339,Research & Development,7,3,Life Sciences,1,86,...,3,NaN,1,25,2.0,3,1,0,0,0.0

In [10]:
df_hr[df_hr.duplicated(keep=False)] #comprobamos sus copias tambien y efectivamente si habia 4 duplicados.nos fijamos en los indices para saber cual es la copia.

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
67,45.0,No,Travel_Rarely,1339,Research & Development,7,3,Life Sciences,1,86,...,3,NaN,1,25,2.0,3,1,0,0,0.0
184,53.0,No,Travel_Rarely,1084,Research & Development,13,2,Medical,1,250,...,3,NaN,2,5,3.0,3,4,2,1,3.0
1041,28.0,No,Travel_Rarely,866,Sales,5,3,Medical,1,1469,...,4,NaN,0,6,4.0,3,5,4,1,NaN
1222,24.0,Yes,Travel_Rarely,240,Human Resources,22,1,Human Resources,1,1714,...,3,80.0,1,1,2.0,3,1,0,0,0.0
1470,28.0,No,Travel_Rarely,866,Sales,5,3,Medical,1,1469,...,4,NaN,0,6,4.0,3,5,4,1,NaN
1471,53.0,No,Travel_Rarely,1084,Research & Development,13,2,Medical,1,250,...,3,NaN,2,5,3.0,3,4,2,1,3.0
1472,24.0,Yes,Travel_Rarely,240,Human Resources,22,1,Human Resources,1,1714,...,3,80.0,1,1,2.0,3,1,0,0,0.0
1473,45.0,No,Travel_Rarely,1339,Research & Development,7,3,Life Sciences,1,86,...,3,NaN,1,25,2.0,3,1,0,0,0.0

In [13]:
 #borramos  los duplicados despues de comprobar.
  df_hr=df_hr.drop_duplicates()

IndentationError: unexpected indent (3089742543.py, line 2)

In [ ]:
df_hr.nunique() #aqui nos muestra que columna tienene el mismo valor.

Age                           43
Attrition                      2
BusinessTravel                 3
DailyRate                    886
Department                     3
DistanceFromHome              29
Education                      5
EducationField                 6
EmployeeCount                  1
EmployeeNumber              1470
EnvironmentSatisfaction        4
Gender                         2
HourlyRate                    71
JobInvolvement                 4
JobLevel                       5
JobRole                        9
JobSatisfaction                4
MaritalStatus                  4
MonthlyIncome               1336
MonthlyRate                 1427
NumCompaniesWorked            10
Over18                         1
OverTime                       2
PercentSalaryHike             15
PerformanceRating              2
RelationshipSatisfaction       4
StandardHours                  1
StockOptionLevel               4
TotalWorkingYears             40
TrainingTimesLastYear          7
WorkLifeBalance                4
YearsAtCompany                37
YearsInCurrentRole            19
YearsSinceLastPromotion       16
YearsWithCurrManager          18
dtype: int64

In [21]:
columnas_texto = df_hr.select_dtypes(include=["string"]) # sacamos todas las columans de string.

In [19]:
columnas_texto.head().T

,0,1,2,3,4
Attrition,Yes,No,Yes,No,No
BusinessTravel,Travel_Rarely,Travel_Frequently,Travel_Rarely,Travel_Frequently,Travel_Rarely
Department,Sales,Research & Development,Research & Development,Research & Development,Research & Development
EducationField,Life Sciences,Life Sciences,Other,Life Sciences,Medical
Gender,Female,Male,Male,Female,Male
JobRole,sALES eXECUTIVE,rESEARCH sCIENTIST,lABORATORY tECHNICIAN,rESEARCH sCIENTIST,lABORATORY tECHNICIAN
MaritalStatus,Single,Married,Single,Married,Married
Over18,Y,Y,Y,Y,Y
OverTime,Yes,No,Yes,Yes,No

In [22]:
columnas_texto.head()
columnas_numeros = df_hr.select_dtypes(include=["number"])
columnas_numeros.head(5).T

                                0        1       2        3        4
Age                          41.0     49.0    37.0     33.0     27.0
DailyRate                  1102.0    279.0  1373.0   1392.0    591.0
DistanceFromHome              1.0      8.0     2.0      3.0      2.0
Education                     2.0      1.0     2.0      4.0      1.0
EmployeeCount                 1.0      1.0     1.0      1.0      1.0
EmployeeNumber                1.0      2.0     4.0      5.0      7.0
EnvironmentSatisfaction       2.0      3.0     4.0      4.0      1.0
HourlyRate                   94.0     61.0    92.0     56.0     40.0
JobInvolvement                3.0      2.0     2.0      3.0      3.0
JobLevel                      2.0      2.0     1.0      1.0      1.0
JobSatisfaction               4.0      2.0     3.0      3.0      2.0
MonthlyIncome              5993.0   5130.0  2090.0   2909.0   3468.0
MonthlyRate               19479.0  24907.0  2396.0  23159.0  16632.0
NumCompaniesWorked            8.0      1.0     6.0      1.0      9.0
PercentSalaryHike            11.0     23.0    15.0     11.0     12.0
PerformanceRating             3.0      4.0     3.0      3.0      3.0
RelationshipSatisfaction      1.0      4.0     2.0      3.0      4.0
StandardHours                80.0      NaN     NaN     80.0     80.0
StockOptionLevel              0.0      1.0     0.0      0.0      1.0
TotalWorkingYears             8.0     10.0     7.0      8.0      6.0
TrainingTimesLastYear         0.0      3.0     3.0      3.0      3.0
WorkLifeBalance               1.0      3.0     3.0      3.0      3.0
YearsAtCompany                6.0     10.0     0.0      8.0      2.0
YearsInCurrentRole            4.0      7.0     0.0      7.0      2.0
YearsSinceLastPromotion       0.0      1.0     0.0      3.0      2.0
YearsWithCurrManager          5.0      7.0     0.0      0.0      2.0

In [36]:
df_hr["TotalWorkingYears"].unique()

array([ 8, 10,  7,  6, 12,  1, 17,  5,  3, 31, 13,  0, 26, 24, 22,  9, 19,
        2, 23, 14, 15,  4, 29, 28, 21, 25, 20, 11, 16, 37, 38, 30, 40, 18,
       36, 34, 32, 33, 35, 27])

In [ ]:
df_hr=df_hr.drop_duplicates()

In [ ]:
df_hr.head().T

,0,1,2,3,4
Age,41.0,49.0,37.0,33.0,27.0
Attrition,Yes,No,Yes,No,No
BusinessTravel,Travel_Rarely,Travel_Frequently,Travel_Rarely,Travel_Frequently,Travel_Rarely
DailyRate,1102,279,1373,1392,591
Department,Sales,Research & Development,Research & Development,Research & Development,Research & Development
DistanceFromHome,1,8,2,3,2
Education,2,1,2,4,1
EducationField,Life Sciences,Life Sciences,Other,Life Sciences,Medical
EmployeeCount,1,1,1,1,1
EmployeeNumber,1,2,4,5,7
EnvironmentSatisfaction,2,3,4,4,1
Gender,Female,Male,Male,Female,Male
HourlyRate,94,61,92,56,40
JobInvolvement,3,2,2,3,3
JobLevel,2,2,1,1,1
JobRole,sALES eXECUTIVE,rESEARCH sCIENTIST,lABORATORY tECHNICIAN,rESEARCH sCIENTIST,lABORATORY tECHNICIAN
JobSatisfaction,4.0,2.0,3.0,3.0,2.0
MaritalStatus,Single,Married,Single,Married,Married
MonthlyIncome,5993.0,5130.0,2090.0,2909.0,3468.0
MonthlyRate,19479,24907,2396,23159,16632
NumCompaniesWorked,8,1,6,1,9
Over18,Y,Y,Y,Y,Y
OverTime,Yes,No,Yes,Yes,No
PercentSalaryHike,11,23,15,11,12
PerformanceRating,3,4,3,3,3
RelationshipSatisfaction,1,4,2,3,4
StandardHours,80.0,NaN,NaN,80.0,80.0
StockOptionLevel,0,1,0,0,1
TotalWorkingYears,8,10,7,8,6
TrainingTimesLastYear,0.0,3.0,3.0,3.0,3.0
WorkLifeBalance,1,3,3,3,3
YearsAtCompany,6,10,0,8,2
YearsInCurrentRole,4,7,0,7,2
YearsSinceLastPromotion,0,1,0,3,2
YearsWithCurrManager,5.0,7.0,0.0,0.0,2.0

In [24]:
#vamos a poner todo el dataframe en minusculas. hay que poner la primera letra en mayuscula.
# aqui pasamos las columnas a minusculas.(fase 2)
for col in df_hr.select_dtypes(include="object"):df_hr[col]=df_hr[col].str.lower()#recorremos todas las columnas y las convertimos a minusculas. solo para texto.

C:\Users\Janira\AppData\Local\Temp\ipykernel_12264\3630780856.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df_hr.select_dtypes(include="object"):df_hr[col]=df_hr[col].str.lower()#recorremos todas las columnas y las convertimos a minusculas. solo para texto.

In [25]:
df_hr.head(5)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41.0,yes,travel_rarely,1102,sales,1,2,life sciences,1,1,...,1,80.0,0,8,0.0,1,6,4,0,5.0
1,49.0,no,travel_frequently,279,research & development,8,1,life sciences,1,2,...,4,NaN,1,10,3.0,3,10,7,1,7.0
2,37.0,yes,travel_rarely,1373,research & development,2,2,other,1,4,...,2,NaN,0,7,3.0,3,0,0,0,0.0
3,33.0,no,travel_frequently,1392,research & development,3,4,life sciences,1,5,...,3,80.0,0,8,3.0,3,8,7,3,0.0
4,27.0,no,travel_rarely,591,research & development,2,1,medical,1,7,...,4,80.0,1,6,3.0,3,2,2,2,2.0

In [ ]:
#vamos a ver el porcentaje  de desercion.
df_hr["attrition"].value_counts(normalize=True) *100#hay un 0.16 de desercion tampoco es tanto, comparado con los que si permanecen en la empresa.

attrition
no     83.85346
yes    16.14654
Name: proportion, dtype: float64

In [ ]:
#vamos a eliminar columnas redundantes. //  dejo la de mayor de 18 años por si entrara algun menor aunque en este analisis actualmente es redundante tambien.
#eliminamos standardhours todas son 80h ,
df_1 = df_hr.drop(['employeecount', 'standardhours'], axis=1, errors='ignore')

In [ ]:
df_1.columns # compruebo que se eliminaron

Index(['age', 'attrition', 'businesstravel', 'dailyrate', 'department',
       'distancefromhome', 'education', 'educationfield', 'employeenumber',
       'environmentsatisfaction', 'gender', 'hourlyrate', 'jobinvolvement',
       'joblevel', 'jobrole', 'jobsatisfaction', 'maritalstatus',
       'monthlyincome', 'monthlyrate', 'numcompaniesworked', 'over18',
       'overtime', 'percentsalaryhike', 'performancerating',
       'relationshipsatisfaction', 'stockoptionlevel', 'totalworkingyears',
       'trainingtimeslastyear', 'worklifebalance', 'yearsatcompany',
       'yearsincurrentrole', 'yearssincelastpromotion',
       'yearswithcurrmanager'],
      dtype='str')